apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-connections
  name: udaconnect-api-connections
spec:
  ports:
  - name: "http"
    port: 5000
    targetPort: 5000
    nodePort: 30004
  selector:
    service: udaconnect-api-connections
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-connections
  name: udaconnect-api-connections
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-connections
  template:
    metadata:
      labels:
        service: udaconnect-api-connections
    spec:
      containers:
      - image: thomasandre/nd064-udaconnect-api-connections:latest
        name: udaconnect-api-connections
        imagePullPolicy: Always
      restartPolicy: Always
