apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-service-locations
  name: udaconnect-service-locations
spec:
  ports:
  - name: "http"
    port: 5000
    targetPort: 5000
  - name: "grpc"
    port: 5005
    targetPort: 5005
  selector:
    service: udaconnect-service-locations
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-service-locations
  name: udaconnect-service-locations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-service-locations
  template:
    metadata:
      labels:
        service: udaconnect-service-locations
    spec:
      containers:
      - image: thomasandre/nd064-udaconnect-service-locations:latest
        name: udaconnect-service-locations
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
