apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-persons
  name: udaconnect-api-persons
spec:
  ports:
  - name: "http"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: udaconnect-api-persons
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-persons
  name: udaconnect-api-persons
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-persons
  template:
    metadata:
      labels:
        service: udaconnect-api-persons
    spec:
      containers:
      - image: thomasandre/nd064-udaconnect-api-persons:latest
        name: udaconnect-api-persons
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: message-env
              key: KAFKA_SERVER
        - name: PERSON_SERVICE
          valueFrom:
            configMapKeyRef:
              name: message-env
              key: PERSON_SERVICE
      restartPolicy: Always
